# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/fralfaro/MAT281_20XX
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/MAT281_20XX
repo_url: https://github.com/fralfaro/MAT281_20XX
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/logo.bmp
  favicon: images/usm.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - index.md
    - Basic Tools:
        - lectures/basic_tools/bt_intro.ipynb
        - lectures/basic_tools/bt_01.ipynb
        - lectures/basic_tools/bt_02.ipynb
        - lectures/basic_tools/bt_03.ipynb
    - Scientific Computing:
        - lectures/data_manipulation/sc_01.ipynb
        - lectures/data_manipulation/sc_02.ipynb
        - lectures/data_manipulation/sc_03.ipynb
    - Data Manipulation:
        - lectures/data_manipulation/pd_intro.ipynb
        - lectures/data_manipulation/pd_01.ipynb
        - lectures/data_manipulation/pd_02.ipynb
        - lectures/data_manipulation/pd_03.ipynb
        - lectures/data_manipulation/pd_04.ipynb
    - Visualization:
        - lectures/data_manipulation/vi_intro.ipynb
        - lectures/data_manipulation/vi_01.ipynb
        - lectures/data_manipulation/vi_02.ipynb
    - EDA:
        - lectures/data_manipulation/eda_intro.md
        - lectures/data_manipulation/eda_01.ipynb
    - Machine Learning:
        - lectures/machine_learning/ml_intro.ipynb
        - lectures/machine_learning/reg_01.ipynb
        - lectures/machine_learning/reg_02.ipynb
        - lectures/machine_learning/cla_01.ipynb
        - lectures/machine_learning/ns_01.ipynb
        - lectures/machine_learning/ns_02.ipynb
        - lectures/machine_learning/over_01.ipynb
        - lectures/machine_learning/over_02.ipynb
        - lectures/machine_learning/ts_01.ipynb


